/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.mjdbapplication.ui;

import com.vektorel.mjdbapplication.data.Kullanici;
import com.vektorel.mjdbapplication.data.Ogrenci;
import com.vektorel.mjdbapplication.data.VeritabaniIslemleri;
import com.vektorel.mjdbapplication.sql.KullaniciSql;
import com.vektorel.mjdbapplication.sql.OgrenciSql;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Emre
 */
public class frmKullaniciEkleGuncelle extends javax.swing.JFrame {
 
    Kullanici kullanici;
    String no;
    VeritabaniIslemleri veritabaniIslemleri = new VeritabaniIslemleri();
    frmKullanicilariListele kullanicilariListele;
    /**
     * Creates new form frmKullaniciEkleGuncelle
     */
    public frmKullaniciEkleGuncelle(Kullanici kullanici) {
        initComponents();
        this.kullanici = kullanici;
        setLocationRelativeTo(null);
        kullanicilariListele = new frmKullanicilariListele(kullanici);
        btnEkle.setVisible(true);
        btnGuncelle.setVisible(false);
        lblAciklama.setText("<html>Lütfen eklemek istediğiniz kullanıcıya ait bütün bilgileri aşağıya yazıp, <br>Ekle düğmesine basınız.");
    }
    
    public frmKullaniciEkleGuncelle(Kullanici kullanici, String no) {
        initComponents();
        this.kullanici = kullanici;
        this.no = no;
        setLocationRelativeTo(null);
        kullanicilariListele = new frmKullanicilariListele(kullanici);
        btnGuncelle.setVisible(true);
        btnEkle.setVisible(false);
        lblAciklama.setText("<html>Lütfen güncellemek istediğiniz bilgileri aşağıya yazıp, <br>Güncelle düğmesine basınız.");
        
        String query = "Select * from kullanici where id=" + no;
        
        try {
            ResultSet resultSet = veritabaniIslemleri.kayitGetir(query);
            
            if (resultSet.next()) {
                txtKullaniciAdi.setText(resultSet.getString("kullanici_adi"));
                txtSifre.setText(resultSet.getString("sifre"));
                txtAdiSoyadi.setText(resultSet.getString("ad_soyad"));
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Kayıt getirilirken bir hata oluştu! Lütfen girdiğiniz No bilgisini kontrol ediniz!", "Hata!!!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAciklama = new javax.swing.JLabel();
        lblKullaniciAdi = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        lblAdiSoyadi = new javax.swing.JLabel();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JPasswordField();
        txtAdiSoyadi = new javax.swing.JTextField();
        btnIptal = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        btnEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAciklama.setText("Açıklama metni");

        lblKullaniciAdi.setText("Kullanıcı Adı:");

        lblSifre.setText("Şifre:");

        lblAdiSoyadi.setText("Adı Soyadı:");

        btnIptal.setText("İptal");
        btnIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIptalActionPerformed(evt);
            }
        });

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAciklama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKullaniciAdi)
                            .addComponent(lblSifre)
                            .addComponent(lblAdiSoyadi))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKullaniciAdi)
                            .addComponent(txtSifre)
                            .addComponent(txtAdiSoyadi)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIptal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciAdi)
                    .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifre)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdiSoyadi)
                    .addComponent(txtAdiSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIptal)
                    .addComponent(btnGuncelle)
                    .addComponent(btnEkle))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        int secim = JOptionPane.showConfirmDialog(rootPane, "İşlemi iptal etmek istiyor musunuz?", "Çıkış", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (secim == 0) {
            kullanicilariListele.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnIptalActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        if (txtKullaniciAdi.getText() != null && txtSifre.getText() != null && txtAdiSoyadi.getText() != null ){

        Kullanici k = new Kullanici();
        k.setKullaniciAdi(txtKullaniciAdi.getText());
        k.setSifre(txtSifre.getText());
        k.setAdSoyad(txtAdiSoyadi.getText());
        
        KullaniciSql kullaniciSql = new KullaniciSql();
        boolean ekleSonuc = kullaniciSql.ekle(k);
                
        if (ekleSonuc)
                JOptionPane.showMessageDialog(rootPane, "Kayıt başarıyla eklendi", "İşlem Tamam", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane, "Kayıt eklenirken bir hata oluştu!", "Hata!!!", JOptionPane.ERROR_MESSAGE);
        
        kullanicilariListele.tabloyuDoldur();
        kullanicilariListele.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        if (txtKullaniciAdi.getText() != null && txtSifre.getText() != null && txtAdiSoyadi.getText() != null ){

        Kullanici k = new Kullanici();
        k.setKullaniciAdi(txtKullaniciAdi.getText());
        k.setSifre(txtSifre.getText());
        k.setAdSoyad(txtAdiSoyadi.getText());
        k.setId(Long.parseLong(no));
        
        KullaniciSql kullaniciSql = new KullaniciSql();
        boolean guncelleSonuc = kullaniciSql.guncelle(k);
        if (guncelleSonuc)
                JOptionPane.showMessageDialog(rootPane, "Kayıt başarıyla güncellendi.", "İşlem Tamam", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane, "Kayıt güncellenirken bir hata oluştu!", "Hata!!!", JOptionPane.ERROR_MESSAGE);
        
        kullanicilariListele.tabloyuDoldur();
        kullanicilariListele.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnIptal;
    private javax.swing.JLabel lblAciklama;
    private javax.swing.JLabel lblAdiSoyadi;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JTextField txtAdiSoyadi;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
