/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.mjdbapplication.ui;

import com.vektorel.mjdbapplication.data.Kullanici;
import com.vektorel.mjdbapplication.data.Ogrenci;
import com.vektorel.mjdbapplication.data.VeritabaniIslemleri;
import com.vektorel.mjdbapplication.sql.OgrenciSql;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Emre
 */
public class frmOgrenciEkleGuncelle extends javax.swing.JFrame {
    
    Kullanici kullanici;
    String no;
    VeritabaniIslemleri veritabaniIslemleri = new VeritabaniIslemleri();
    frmAnaSayfa anaSayfa;

    public frmOgrenciEkleGuncelle(Kullanici kullanici) {
        initComponents();
        this.kullanici = kullanici;
        setLocationRelativeTo(null);
        anaSayfa = new frmAnaSayfa(kullanici);
        btnEkle.setVisible(true);
        btnGuncelle.setVisible(false);
        lblAciklama.setText("<html>Lütfen eklemek istediğiniz öğrenciye ait bütün bilgileri aşağıya yazıp, <br>Ekle düğmesine basınız.");
        
    }
    
    public frmOgrenciEkleGuncelle(Kullanici kullanici, String no) {
        initComponents();
        this.kullanici = kullanici;
        this.no = no;
        setLocationRelativeTo(null);
        anaSayfa = new frmAnaSayfa(kullanici);
        btnGuncelle.setVisible(true);
        btnEkle.setVisible(false);
        lblAciklama.setText("<html>Lütfen güncellemek istediğiniz bilgileri aşağıya yazıp, <br>Güncelle düğmesine basınız.");
        
        String query = "Select * from ogrenci where id=" + no;
        
        try {
            ResultSet resultSet = veritabaniIslemleri.kayitGetir(query);
            
            if (resultSet.next()) {
                txtAdi.setText(resultSet.getString("ad"));
                txtSoyadi.setText(resultSet.getString("soyad"));
                txtYas.setText(String.valueOf(resultSet.getInt("yas")));
                txtBolumAdi.setText(resultSet.getString("bolum_adi"));
                txtOkulNo.setText(resultSet.getString("okul_no"));
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Kayıt getirilirken bir hata oluştu! Lütfen girdiğiniz No bilgisini kontrol ediniz!", "Hata!!!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdi = new javax.swing.JLabel();
        lblSoyadi = new javax.swing.JLabel();
        lblYas = new javax.swing.JLabel();
        lblOkulNo = new javax.swing.JLabel();
        lblBolumNo = new javax.swing.JLabel();
        txtBolumAdi = new javax.swing.JTextField();
        txtOkulNo = new javax.swing.JTextField();
        txtYas = new javax.swing.JTextField();
        txtSoyadi = new javax.swing.JTextField();
        txtAdi = new javax.swing.JTextField();
        btnIptal = new javax.swing.JButton();
        btnEkle = new javax.swing.JButton();
        lblAciklama = new javax.swing.JLabel();
        btnGuncelle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdi.setText("Adı:");

        lblSoyadi.setText("Soyadı:");

        lblYas.setText("Yaşı:");

        lblOkulNo.setText("Okul No:");

        lblBolumNo.setText("Bölüm Adı:");

        btnIptal.setText("İptal");
        btnIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIptalActionPerformed(evt);
            }
        });

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        lblAciklama.setText("Açıklama metni");

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAciklama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBolumNo)
                            .addComponent(lblOkulNo)
                            .addComponent(lblYas)
                            .addComponent(lblSoyadi)
                            .addComponent(lblAdi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOkulNo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIptal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBolumAdi)
                            .addComponent(txtYas)
                            .addComponent(txtSoyadi)
                            .addComponent(txtAdi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblAciklama, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdi)
                    .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoyadi)
                    .addComponent(txtSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYas)
                    .addComponent(txtYas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOkulNo)
                    .addComponent(txtOkulNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBolumNo)
                    .addComponent(txtBolumAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIptal)
                    .addComponent(btnEkle)
                    .addComponent(btnGuncelle))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        if (txtAdi.getText() != null && txtSoyadi.getText() != null && txtYas.getText() != null && txtBolumAdi.getText() != null && txtOkulNo.getText() != null){

        Ogrenci o = new Ogrenci();
        o.setAd(txtAdi.getText());
        o.setSoyad(txtSoyadi.getText());
        o.setYas(Integer.parseInt(txtYas.getText()));
        o.setOkulNo(txtOkulNo.getText());
        o.setBolumAdi(txtBolumAdi.getText());
        
        OgrenciSql ogrenciSql = new OgrenciSql();
        boolean ekleSonuc = ogrenciSql.ekle(o);
                
        if (ekleSonuc)
                JOptionPane.showMessageDialog(rootPane, "Kayıt başarıyla eklendi", "İşlem Tamam", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane, "Kayıt eklenirken bir hata oluştu!", "Hata!!!", JOptionPane.ERROR_MESSAGE);
        
        anaSayfa.tabloyuDoldur();
        anaSayfa.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        int secim = JOptionPane.showConfirmDialog(rootPane, "İşlemi iptal etmek istiyor musunuz?", "Çıkış", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (secim == 0) {
            anaSayfa.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnIptalActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed

    if (txtAdi.getText() != null && txtSoyadi.getText() != null && txtYas.getText() != null && txtBolumAdi.getText() != null && txtOkulNo.getText() != null){

        Ogrenci o = new Ogrenci();
        o.setAd(txtAdi.getText());
        o.setSoyad(txtSoyadi.getText());
        o.setYas(Integer.parseInt(txtYas.getText()));
        o.setOkulNo(txtOkulNo.getText());
        o.setBolumAdi(txtBolumAdi.getText());
        o.setId(Long.parseLong(no));
        
        OgrenciSql ogrenciSql = new OgrenciSql();
        boolean guncelleSonuc = ogrenciSql.guncelle(o);
        if (guncelleSonuc)
                JOptionPane.showMessageDialog(rootPane, "Kayıt başarıyla güncellendi.", "İşlem Tamam", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane, "Kayıt güncellenirken bir hata oluştu!", "Hata!!!", JOptionPane.ERROR_MESSAGE);
        
        anaSayfa.tabloyuDoldur();
        anaSayfa.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnIptal;
    private javax.swing.JLabel lblAciklama;
    private javax.swing.JLabel lblAdi;
    private javax.swing.JLabel lblBolumNo;
    private javax.swing.JLabel lblOkulNo;
    private javax.swing.JLabel lblSoyadi;
    private javax.swing.JLabel lblYas;
    private javax.swing.JTextField txtAdi;
    private javax.swing.JTextField txtBolumAdi;
    private javax.swing.JTextField txtOkulNo;
    private javax.swing.JTextField txtSoyadi;
    private javax.swing.JTextField txtYas;
    // End of variables declaration//GEN-END:variables
}
